// Static meaning lookups for panchang elements that panchang-ts doesn't annotate.
// Keys match the English names returned by getDailyPanchang with language:'en'.

export const NAKSHATRA_MEANINGS: Record<string, string> = {
  Ashwini: "Horse's Head",
  Bharani: "Bearer",
  Krittika: "The Pleiades",
  Rohini: "Ascending Star",
  Mrigashira: "Deer's Head",
  Ardra: "Moist / Teardrop",
  Punarvasu: "Return of Light",
  Pushya: "Nourisher",
  Ashlesha: "Clinging Star",
  Magha: "The Mighty",
  "Purva Phalguni": "First Reddish Star",
  "Uttara Phalguni": "Second Reddish Star",
  Hasta: "The Hand",
  Chitra: "Bright / Beautiful",
  Swati: "Fresh / Independent",
  Vishakha: "Forked Branch",
  Anuradha: "Following Radha",
  Jyeshtha: "The Eldest",
  Mula: "The Root",
  "Purva Ashadha": "Early Victory",
  "Uttara Ashadha": "Final Victory",
  Shravana: "Hearing / The Ear",
  Dhanishtha: "Most Auspicious",
  Shatabhisha: "Hundred Healers",
  "Purva Bhadrapada": "First Auspicious Step",
  "Uttara Bhadrapada": "Second Auspicious Step",
  Revati: "Wealthy / Prosperous",
};

export const YOGA_MEANINGS: Record<string, string> = {
  Vishkambha: "Obstacle-Remover",
  Priti: "Love & Affection",
  Ayushman: "Long Life",
  Saubhagya: "Good Fortune",
  Shobhana: "Radiant",
  Atiganda: "Danger",
  Sukarma: "Good Deeds",
  Dhriti: "Determination",
  Shula: "Sharp Edge",
  Ganda: "Knot / Danger",
  Vriddhi: "Growth",
  Dhruva: "Constant / Fixed",
  Vyaghata: "Strike",
  Harshana: "Joy",
  Vajra: "Thunderbolt",
  Siddhi: "Accomplishment",
  Vyatipata: "Calamity",
  Variyana: "Excellent",
  Parigha: "Obstruction",
  Shiva: "Auspicious",
  Siddha: "Achieved",
  Sadhya: "Attainable",
  Shubha: "Auspicious",
  Shukla: "Bright / Pure",
  Brahma: "Creative",
  Indra: "Powerful",
  Vaidhriti: "Poor Support",
};

// Sanskrit vara name → deity string (mirrors vara_rules.json)
export const VARA_DEITIES: Record<string, string> = {
  Raviwara: "Surya",
  Somawara: "Shiva & Chandra",
  Mangalawara: "Hanuman",
  Budhawara: "Budha",
  Guruwara: "Vishnu & Brihaspati",
  Shukrawara: "Lakshmi",
  Shaniwara: "Shani",
};
